### ISSUE TITLE
Dict training segfaults with small value of maxdict

### ISSUE THREAD

**Issue by Gyscos** [Cyan4973/zstd#131]
Using git version c580b75, tagged v0.5.1.
When running `programs/zstd --train lib/*.c --maxdict 1024` (creating a dictionary from zstd's own source code), I get a segfault. Backtracking gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000040be88 in FSE_encodeSymbol (bitC=0x7fffffffc4e0, statePtr=0x7fffffffc480, symbol=216) at ../lib/fse_static.h:261
261	    statePtr->value = stateTable[ (statePtr->value >> nbBitsOut) + symbolTT.deltaFindState];
(gdb) bt
#0  0x000000000040be88 in FSE_encodeSymbol (bitC=0x7fffffffc4e0, statePtr=0x7fffffffc480, symbol=216) at ../lib/fse_static.h:261
#1  0x000000000040dd35 in ZSTD_compressSequences (zc=0x6ea200, dst=0x6ebe50, maxDstSize=131072, srcSize=97838) at ../lib/zstd_compress.c:697
#2  0x00000000004281ea in ZSTD_compressBlock_internal (zc=0x6ea200, dst=0x6ebe50, maxDstSize=131072, src=0x6a8ddf, srcSize=97838) at ../lib/zstd_compress.c:1909
#3  0x000000000042872f in ZSTD_compressContinue_internal (zc=0x6ea200, dst=0x6ebe50, dstSize=131072, src=0x6a8ddf, srcSize=97838, frame=0) at ../lib/zstd_compress.c:2014
#4  0x00000000004287ed in ZSTD_compressBlock (zc=0x6ea200, dst=0x6ebe50, maxDstSize=131072, src=0x6a8ddf, srcSize=97838) at ../lib/zstd_compress.c:2032
#5  0x000000000044afe0 in ZDICT_countEStats (esr=..., countLit=0x7fffffffd540, offsetcodeCount=0x7fffffffd4c0, matchlengthCount=0x7fffffffce80, litlengthCount=0x7fffffffcc80, src=0x6a8ddf, srcSize=97838) at ../lib/zdict.c:604
#6  0x000000000044b379 in ZDICT_analyzeEntropy (dstBuffer=0x6730b4, maxDstSize=1020, compressionLevel=5, srcBuffer=0x6734c0, fileSizes=0x673070, nbFiles=7, dictBuffer=0x6731de, dictBufferSize=722) at ../lib/zdict.c:662
#7  0x000000000044be7c in ZDICT_trainFromBuffer_unsafe (dictBuffer=0x6730b0, maxDictSize=1024, samplesBuffer=0x6734c0, sampleSizes=0x673070, nbSamples=7, params=...) at ../lib/zdict.c:873
#8  0x0000000000461923 in DiB_trainFromFiles (dictFileName=0x465f98 "dictionary", maxDictSize=1024, fileNamesTable=0x673010, nbFiles=7, params=...) at dibio.c:258
#9  0x0000000000456b14 in main (argCount=11, argv=0x7fffffffdc98) at zstdcli.c:381

```

Is there some minimum size the dictionary requires to properly initialize?
EDIT: still happens on the `dev` branch.

**Comment by Cyan4973** [comment]
Thanks for notification.

> Is there some minimum size the dictionary requires to properly initialize?

Maybe it should :)

**Comment by Cyan4973** [comment]
Latest update in "dev" branch should fix this issue.

The program check for a very minimum dictionary size (a few hundred bytes), below which there is basically no space left to work.
But of course, dictionary lose its efficiency before reaching such unreasonable levels.
