### ISSUE TITLE
Out of bounds heap read in ZSTD_copy8

### ISSUE THREAD

**Issue by hannob** [Cyan4973/zstd#50]
This file
https://crashes.fuzzing-project.org/zstd-oob-heap-ZSTD_copy8
causes an out of bounds heap read access in zstd. This can be seen with either address sanitizer or valgrind.

This was found with american fuzzy lop.

Address Sanitizer output:
```
==12888==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fc173c8104b at pc 0x0000004e939f bp 0x7ffe115e1a50 sp 0x7ffe115e1a48
READ of size 8 at 0x7fc173c8104b thread T0
    #0 0x4e939e in ZSTD_copy8 /f/zst/zstd/programs/../lib/zstd.c:158:56
    #1 0x4e939e in ZSTD_wildcopy /f/zst/zstd/programs/../lib/zstd.c:168
    #2 0x4e939e in ZSTD_execSequence /f/zst/zstd/programs/../lib/zstd.c:1337
    #3 0x4e939e in ZSTD_decompressSequences /f/zst/zstd/programs/../lib/zstd.c:1436
    #4 0x4e939e in ZSTD_decompressBlock /f/zst/zstd/programs/../lib/zstd.c:1473
    #5 0x4e68b2 in ZSTD_decompressContinue /f/zst/zstd/programs/../lib/zstd.c:1622:21
    #6 0x52dcbf in FIO_decompressFrame /f/zst/zstd/programs/fileio.c:396:23
    #7 0x52e721 in FIO_decompressFilename /f/zst/zstd/programs/fileio.c:492:21
    #8 0x530fe3 in main /f/zst/zstd/programs/zstdcli.c:352:9
    #9 0x7fc172bf4f9f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.20-r2/work/glibc-2.20/csu/libc-start.c:289
    #10 0x4377c6 in _start (/mnt/ram/zstd/zstd+0x4377c6)

0x7fc173c8104b is located 3 bytes to the right of 141384-byte region [0x7fc173c5e800,0x7fc173c81048)
allocated by thread T0 here:
    #0 0x4be792 in __interceptor_malloc (/mnt/ram/zstd/zstd+0x4be792)
    #1 0x4e627c in ZSTD_createDCtx /f/zst/zstd/programs/../lib/zstd.c:1560:35
    #2 0x530fe3 in main /f/zst/zstd/programs/zstdcli.c:352:9

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/zst/zstd/programs/../lib/zstd.c:158 ZSTD_copy8
Shadow bytes around the buggy address:
  0x0ff8ae7881b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff8ae7881c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff8ae7881d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff8ae7881e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff8ae7881f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff8ae788200: 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa
  0x0ff8ae788210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff8ae788220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff8ae788230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff8ae788240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff8ae788250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12888==ABORTING

**Comment by Cyan4973** [comment]
The issue should be fixed within latest update of "dev" branch

**Comment by hannob** [comment]
also here: can confirm fix works.
